### ISSUE TITLE
Exome kit support

### ISSUE THREAD

**Issue by egeulgen** [McGranahanLab/TcellExTRECT#10]
Firstly, thank you for this brilliant tool!

I'd like to use the tool on our WES cohort for which 3-4 different exome capture kits were used. If possible, could you provide a script or steps on how to create the exon positions table for the TCRA locus.

Should this be exons of TCRA overlapping with the target regions of the kit or?

Best,
-E

**Comment by haixiashang** [comment]
Hi! Thank you for such cool tool! 
I have some questions:
When I run your code, I noticed that there are two parameters median.k=50, median.threshold=15, do I need to adjust the two parameters?
I use your example data as input, the output figure is the same with your paper,
but, when I use our own data as input, the output figure is not similar with yours.
[question_data.pdf](https://github.com/McGranahanLab/TcellExTRECT/files/7491941/question_data.pdf)
I dno't known how to solve this kind of problem.

**Comment by rbentham** [comment]
Hi, 
median.k sets the width of a rolling window used in one of the normalisation steps and median.theshold sets a threshold so that the median of each exon with coverage is above a certain number. I do not think you would need to change the median.k parameter and the median.threshold parameter should only be lowered if you have very low coverage.  

Looking at your output figure I don't think either of these parameters need to be changed. What capture kit are you using? If it is agilent v2 make sure you are using the data file specific to that kit. In general the output looks noisy but this could just mean that there is very little T cell infiltration within your sample.

**Comment by haixiashang** [comment]
thanks , got it!



发自我的iPhone


------------------ Original ------------------
From: Robert Bentham ***@***.***&gt;
Date: Mon,Nov 8,2021 5:53 PM
To: McGranahanLab/TcellExTRECT ***@***.***&gt;
Cc: haixiashang ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [McGranahanLab/TcellExTRECT] Exome kit support (#10)





 
Hi,
 median.k sets the width of a rolling window used in one of the normalisation steps and median.theshold sets a threshold so that the median of each exon with coverage is above a certain number. I do not think you would need to change the median.k parameter and the median.threshold parameter should only be lowered if you have very low coverage.
 
Looking at your output figure I don't think either of these parameters need to be changed. What capture kit are you using? If it is agilent v2 make sure you are using the data file specific to that kit. In general the output looks noisy but this could just mean that there is very little T cell infiltration within your sample.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
