### ISSUE TITLE
Negative values for TCRA.tcell.fraction

### ISSUE THREAD

**Issue by egeulgen** [McGranahanLab/TcellExTRECT#11]
Hello again,

For some samples, `runTcellExTRECT()` results in negative values (e.g., -7.815970e-14, -6.172840e-14 etc.) for `TCRA.tcell.fraction`. Should I be interpreting these as no infiltration or could there be an issue with these samples?

-E

**Comment by rbentham** [comment]
Hi,

There is nothing wrong with the samples in these cases. Very small negative values e.g. ~e-14 should be interpreted as 0 or no infiltration. This is due to the way the model is being fitted and while the minimum value in theory is 0 there is a very small amount of numerical noise in the current implementation of T cell ExTRECT which can cause the value to become negative. I will look into seeing if there is a simple way of adapting the code so that there are no negative values.

**Comment by rbentham** [comment]
The number of no infiltration samples will be very dependent on the data set you are looking at, if this was a low T cell infiltration cancer type that many with no infiltration detected would not be unusual.
