### ISSUE TITLE
gratia Dependency

### ISSUE THREAD

**Issue by DarioS** [McGranahanLab/TcellExTRECT#4]
It is a plotting package. Should it really be in Depends? The vignette doesn't demonstrate any plots. Suggests instead, perhaps?
Also, it leads to installation errors on the university's H.P.C., preventing TcellExTRECT from installing.

```
WARNING: this compiler is pretending to be GCC but it may not be fully compatible;
WARNING: to allow this compiler to use GCC features such as data alignment attributes,
WARNING: #define ARMA_ALLOW_FAKE_GCC before #include <armadillo>
icpc -std=gnu++11 -shared -L/apps/R/4.1.0/lib64/R/lib -L/usr/local/lib64 -o RcppArmadillo.so RcppArmadillo.o RcppExports.o fastLm.o -L/lib/intel64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lifport -lifcoremt -limf -lsvml -lm -lipgo -lirc -lpthread -lirc_s -ldl -L/apps/R/4.1.0/lib64/R/lib -lR
/bin/ld: cannot find -lmkl_intel_lp64
/bin/ld: cannot find -lmkl_intel_thread
/bin/ld: cannot find -lmkl_core
make: *** [/apps/R/4.1.0/lib64/R/share/make/shlib.mk:10: RcppArmadillo.so] Error 1
ERROR: compilation failed for package 'RcppArmadillo'
```

**Comment by rbentham** [comment]
The gratia package also contains 'utility functions for working with generalized additive models (GAMs) fitted using the 'mgcv' package', particularly a non-exported method from gratia for the confidence interval function `confint()` to work on GAM models is needed in T cell ExTRECT which is why it is listed as a dependency.  

I am sorry I am not sure how to help with the installation on your HPC, but the issue looks like it is with RcppArmadillo and not T cell ExTRECT or gratia?
